DO $$
DECLARE
    auth_relation_count integer;
    non_table_relations text;
BEGIN
    SELECT count(*)
      INTO auth_relation_count
      FROM pg_class AS relation
      JOIN pg_namespace AS namespace ON namespace.oid = relation.relnamespace
     WHERE namespace.nspname = 'public'
       AND relation.relname IN (
           'internal_users',
           'external_identities',
           'registered_web_services'
       );

    IF auth_relation_count NOT IN (0, 3) THEN
        RAISE EXCEPTION
            'authentication tables must be all absent or all present; found % of 3',
            auth_relation_count;
    END IF;

    IF auth_relation_count = 3 THEN
        SELECT string_agg(relation.relname, ', ' ORDER BY relation.relname)
          INTO non_table_relations
          FROM pg_class AS relation
          JOIN pg_namespace AS namespace ON namespace.oid = relation.relnamespace
         WHERE namespace.nspname = 'public'
           AND relation.relname IN (
               'internal_users',
               'external_identities',
               'registered_web_services'
           )
           AND relation.relkind <> 'r';

        IF non_table_relations IS NOT NULL THEN
            RAISE EXCEPTION
                'authentication table structure mismatch: expected ordinary tables, found %',
                non_table_relations;
        END IF;
    END IF;
END
$$;

DO $$
DECLARE
    auth_relation_count integer;
BEGIN
    SELECT count(*)
      INTO auth_relation_count
      FROM pg_class AS relation
      JOIN pg_namespace AS namespace ON namespace.oid = relation.relnamespace
     WHERE namespace.nspname = 'public'
       AND relation.relname IN (
           'internal_users',
           'external_identities',
           'registered_web_services'
       );

    IF auth_relation_count = 0 THEN
        EXECUTE $ddl$
            CREATE TABLE public.internal_users (
                internal_user_id integer GENERATED BY DEFAULT AS IDENTITY,
                is_enabled boolean NOT NULL DEFAULT true,
                created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
                CONSTRAINT internal_users_pkey PRIMARY KEY (internal_user_id)
            )
        $ddl$;

        EXECUTE $ddl$
            CREATE TABLE public.external_identities (
                provider text NOT NULL,
                subject text NOT NULL,
                internal_user_id integer NOT NULL,
                linked_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
                CONSTRAINT external_identities_pkey PRIMARY KEY (provider, subject),
                CONSTRAINT external_identities_provider_not_empty CHECK (length(provider) > 0),
                CONSTRAINT external_identities_subject_not_empty CHECK (length(subject) > 0),
                CONSTRAINT external_identities_internal_user_fk
                    FOREIGN KEY (internal_user_id)
                    REFERENCES public.internal_users (internal_user_id)
                    ON DELETE NO ACTION
            )
        $ddl$;

        EXECUTE $ddl$
            CREATE INDEX external_identities_internal_user_id_idx
                ON public.external_identities (internal_user_id)
        $ddl$;

        EXECUTE $ddl$
            CREATE TABLE public.registered_web_services (
                service_id text NOT NULL,
                is_enabled boolean NOT NULL DEFAULT true,
                login_callback_uri text NOT NULL,
                logout_return_uri text NOT NULL,
                service_secret_sha256 bytea NOT NULL,
                created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
                CONSTRAINT registered_web_services_pkey PRIMARY KEY (service_id),
                CONSTRAINT registered_web_services_service_id_format
                    CHECK (service_id ~ '^[a-z0-9][a-z0-9_-]{0,63}$'),
                CONSTRAINT registered_web_services_login_callback_uri_not_empty
                    CHECK (length(login_callback_uri) > 0),
                CONSTRAINT registered_web_services_logout_return_uri_not_empty
                    CHECK (length(logout_return_uri) > 0),
                CONSTRAINT registered_web_services_service_secret_sha256_length
                    CHECK (octet_length(service_secret_sha256) = 32)
            )
        $ddl$;
    END IF;
END
$$;

DO $$
DECLARE
    auth_table_name text;
    expected_columns text[];
    actual_columns text[];
    actual_column_count integer;
    mismatch_detail text;
    validation_enabled boolean;
    validation_time timestamptz;
BEGIN
    IF EXISTS (
        SELECT 1
          FROM pg_class AS relation
          JOIN pg_namespace AS namespace ON namespace.oid = relation.relnamespace
         WHERE namespace.nspname = 'public'
           AND relation.relname IN (
               'internal_users',
               'external_identities',
               'registered_web_services'
           )
           AND (
               relation.relkind <> 'r'
               OR relation.relpersistence <> 'p'
               OR relation.relispartition
               OR EXISTS (
                   SELECT 1
                     FROM pg_inherits AS inheritance
                    WHERE inheritance.inhrelid = relation.oid
                       OR inheritance.inhparent = relation.oid
               )
           )
    ) THEN
        RAISE EXCEPTION
            'authentication table structure mismatch: tables must be permanent, ordinary, non-partitioned, and non-inherited';
    END IF;

    FOREACH auth_table_name IN ARRAY ARRAY[
        'internal_users',
        'external_identities',
        'registered_web_services'
    ] LOOP
        SELECT array_agg(attribute.attname ORDER BY attribute.attnum), count(*)
          INTO actual_columns, actual_column_count
          FROM pg_attribute AS attribute
         WHERE attribute.attrelid = format('public.%I', auth_table_name)::regclass
           AND attribute.attnum > 0
           AND NOT attribute.attisdropped;

        expected_columns := CASE auth_table_name
            WHEN 'internal_users' THEN ARRAY[
                'internal_user_id', 'is_enabled', 'created_at'
            ]
            WHEN 'external_identities' THEN ARRAY[
                'provider', 'subject', 'internal_user_id', 'linked_at'
            ]
            WHEN 'registered_web_services' THEN ARRAY[
                'service_id', 'is_enabled', 'login_callback_uri',
                'logout_return_uri', 'service_secret_sha256', 'created_at'
            ]
        END;

        IF actual_column_count <> cardinality(expected_columns)
           OR actual_columns IS DISTINCT FROM expected_columns THEN
            RAISE EXCEPTION
                'authentication table structure mismatch: public.% columns expected %, found %',
                auth_table_name, expected_columns, actual_columns;
        END IF;
    END LOOP;

    WITH expected_columns (
        table_name,
        column_name,
        column_type,
        not_null,
        identity_kind,
        default_required
    ) AS (
        VALUES
            ('internal_users', 'internal_user_id', 'integer', true, 'd', false),
            ('internal_users', 'is_enabled', 'boolean', true, '', true),
            ('internal_users', 'created_at', 'timestamp with time zone', true, '', true),
            ('external_identities', 'provider', 'text', true, '', false),
            ('external_identities', 'subject', 'text', true, '', false),
            ('external_identities', 'internal_user_id', 'integer', true, '', false),
            ('external_identities', 'linked_at', 'timestamp with time zone', true, '', true),
            ('registered_web_services', 'service_id', 'text', true, '', false),
            ('registered_web_services', 'is_enabled', 'boolean', true, '', true),
            ('registered_web_services', 'login_callback_uri', 'text', true, '', false),
            ('registered_web_services', 'logout_return_uri', 'text', true, '', false),
            ('registered_web_services', 'service_secret_sha256', 'bytea', true, '', false),
            ('registered_web_services', 'created_at', 'timestamp with time zone', true, '', true)
    ), actual_columns AS (
        SELECT
            expected.table_name,
            expected.column_name,
            expected.column_type,
            expected.not_null,
            expected.identity_kind,
            expected.default_required,
            format_type(attribute.atttypid, attribute.atttypmod) AS actual_type,
            attribute.attnotnull AS actual_not_null,
            attribute.attidentity AS actual_identity_kind,
            default_value.oid IS NOT NULL AS has_default
          FROM expected_columns AS expected
          JOIN pg_attribute AS attribute
            ON attribute.attrelid = format('public.%I', expected.table_name)::regclass
           AND attribute.attname = expected.column_name
           AND attribute.attnum > 0
           AND NOT attribute.attisdropped
          LEFT JOIN pg_attrdef AS default_value
            ON default_value.adrelid = attribute.attrelid
           AND default_value.adnum = attribute.attnum
    )
    SELECT string_agg(
               format('%s.%s (type=%s, not_null=%s, identity=%s, has_default=%s)',
                   table_name,
                   column_name,
                   actual_type,
                   actual_not_null,
                   actual_identity_kind,
                   has_default
               ),
               '; ' ORDER BY table_name, column_name
           )
      INTO mismatch_detail
      FROM actual_columns
     WHERE actual_type <> column_type
        OR actual_not_null IS DISTINCT FROM not_null
        OR actual_identity_kind IS DISTINCT FROM identity_kind
        OR has_default IS DISTINCT FROM default_required;

    IF mismatch_detail IS NOT NULL THEN
        RAISE EXCEPTION
            'authentication table column definition mismatch: %',
            mismatch_detail;
    END IF;

    IF EXISTS (
        SELECT 1
          FROM pg_constraint AS constraint_definition
         WHERE constraint_definition.conrelid IN (
             'public.internal_users'::regclass,
             'public.external_identities'::regclass,
             'public.registered_web_services'::regclass
         )
           AND constraint_definition.contype NOT IN ('p', 'f', 'c')
    ) THEN
        RAISE EXCEPTION
            'authentication table structure mismatch: unexpected constraint type';
    END IF;

    IF (SELECT count(*) FROM pg_constraint
         WHERE conrelid = 'public.internal_users'::regclass AND contype = 'p') <> 1
       OR NOT EXISTS (
           SELECT 1 FROM pg_constraint AS constraint_definition
            WHERE constraint_definition.conrelid = 'public.internal_users'::regclass
              AND constraint_definition.conname = 'internal_users_pkey'
              AND constraint_definition.contype = 'p'
              AND constraint_definition.conkey = ARRAY[
                  (SELECT attnum FROM pg_attribute
                    WHERE attrelid = 'public.internal_users'::regclass
                      AND attname = 'internal_user_id')
              ]::smallint[]
       ) THEN
        RAISE EXCEPTION
            'authentication table structure mismatch: internal_users primary key';
    END IF;

    IF (SELECT count(*) FROM pg_constraint
         WHERE conrelid = 'public.external_identities'::regclass AND contype = 'p') <> 1
       OR NOT EXISTS (
           SELECT 1 FROM pg_constraint AS constraint_definition
            WHERE constraint_definition.conrelid = 'public.external_identities'::regclass
              AND constraint_definition.conname = 'external_identities_pkey'
              AND constraint_definition.contype = 'p'
              AND constraint_definition.conkey = ARRAY[
                  (SELECT attnum FROM pg_attribute
                    WHERE attrelid = 'public.external_identities'::regclass
                      AND attname = 'provider'),
                  (SELECT attnum FROM pg_attribute
                    WHERE attrelid = 'public.external_identities'::regclass
                      AND attname = 'subject')
              ]::smallint[]
       ) THEN
        RAISE EXCEPTION
            'authentication table structure mismatch: external_identities primary key';
    END IF;

    IF (SELECT count(*) FROM pg_constraint
         WHERE conrelid = 'public.registered_web_services'::regclass AND contype = 'p') <> 1
       OR NOT EXISTS (
           SELECT 1 FROM pg_constraint AS constraint_definition
            WHERE constraint_definition.conrelid = 'public.registered_web_services'::regclass
              AND constraint_definition.conname = 'registered_web_services_pkey'
              AND constraint_definition.contype = 'p'
              AND constraint_definition.conkey = ARRAY[
                  (SELECT attnum FROM pg_attribute
                    WHERE attrelid = 'public.registered_web_services'::regclass
                      AND attname = 'service_id')
              ]::smallint[]
       ) THEN
        RAISE EXCEPTION
            'authentication table structure mismatch: registered_web_services primary key';
    END IF;

    IF (SELECT count(*) FROM pg_constraint
         WHERE conrelid = 'public.external_identities'::regclass AND contype = 'f') <> 1
       OR NOT EXISTS (
           SELECT 1 FROM pg_constraint AS constraint_definition
            WHERE constraint_definition.conrelid = 'public.external_identities'::regclass
              AND constraint_definition.conname = 'external_identities_internal_user_fk'
              AND constraint_definition.contype = 'f'
              AND constraint_definition.conkey = ARRAY[
                  (SELECT attnum FROM pg_attribute
                    WHERE attrelid = 'public.external_identities'::regclass
                      AND attname = 'internal_user_id')
              ]::smallint[]
              AND constraint_definition.confrelid = 'public.internal_users'::regclass
              AND constraint_definition.confkey = ARRAY[
                  (SELECT attnum FROM pg_attribute
                    WHERE attrelid = 'public.internal_users'::regclass
                      AND attname = 'internal_user_id')
              ]::smallint[]
              AND constraint_definition.confdeltype = 'a'
              AND constraint_definition.confupdtype = 'a'
              AND constraint_definition.confmatchtype = 's'
              AND NOT constraint_definition.condeferrable
              AND NOT constraint_definition.condeferred
              AND constraint_definition.convalidated
       ) THEN
        RAISE EXCEPTION
            'authentication table structure mismatch: external_identities foreign key';
    END IF;

    IF EXISTS (
        SELECT 1
          FROM pg_constraint AS constraint_definition
         WHERE constraint_definition.conrelid IN (
             'public.internal_users'::regclass,
             'public.external_identities'::regclass,
             'public.registered_web_services'::regclass
         )
           AND constraint_definition.contype = 'f'
           AND constraint_definition.conrelid <> 'public.external_identities'::regclass
    ) THEN
        RAISE EXCEPTION
            'authentication table structure mismatch: unexpected foreign key';
    END IF;

    IF (SELECT count(*) FROM pg_constraint
         WHERE conrelid = 'public.internal_users'::regclass AND contype = 'c') <> 0
       OR (SELECT count(*) FROM pg_constraint
           WHERE conrelid = 'public.external_identities'::regclass AND contype = 'c') <> 2
       OR (SELECT count(*) FROM pg_constraint
           WHERE conrelid = 'public.registered_web_services'::regclass AND contype = 'c') <> 4
       OR NOT EXISTS (
           SELECT 1
             FROM pg_constraint AS constraint_definition
            WHERE constraint_definition.conrelid = 'public.external_identities'::regclass
              AND constraint_definition.conname = 'external_identities_provider_not_empty'
              AND constraint_definition.contype = 'c'
              AND constraint_definition.convalidated
              AND constraint_definition.conkey = ARRAY[
                  (SELECT attnum FROM pg_attribute
                    WHERE attrelid = 'public.external_identities'::regclass
                      AND attname = 'provider')
              ]::smallint[]
       )
       OR NOT EXISTS (
           SELECT 1
             FROM pg_constraint AS constraint_definition
            WHERE constraint_definition.conrelid = 'public.external_identities'::regclass
              AND constraint_definition.conname = 'external_identities_subject_not_empty'
              AND constraint_definition.contype = 'c'
              AND constraint_definition.convalidated
              AND constraint_definition.conkey = ARRAY[
                  (SELECT attnum FROM pg_attribute
                    WHERE attrelid = 'public.external_identities'::regclass
                      AND attname = 'subject')
              ]::smallint[]
       )
       OR NOT EXISTS (
           SELECT 1
             FROM pg_constraint AS constraint_definition
            WHERE constraint_definition.conrelid = 'public.registered_web_services'::regclass
              AND constraint_definition.conname = 'registered_web_services_service_id_format'
              AND constraint_definition.contype = 'c'
              AND constraint_definition.convalidated
              AND constraint_definition.conkey = ARRAY[
                  (SELECT attnum FROM pg_attribute
                    WHERE attrelid = 'public.registered_web_services'::regclass
                      AND attname = 'service_id')
              ]::smallint[]
       )
       OR NOT EXISTS (
           SELECT 1
             FROM pg_constraint AS constraint_definition
            WHERE constraint_definition.conrelid = 'public.registered_web_services'::regclass
              AND constraint_definition.conname = 'registered_web_services_login_callback_uri_not_empty'
              AND constraint_definition.contype = 'c'
              AND constraint_definition.convalidated
              AND constraint_definition.conkey = ARRAY[
                  (SELECT attnum FROM pg_attribute
                    WHERE attrelid = 'public.registered_web_services'::regclass
                      AND attname = 'login_callback_uri')
              ]::smallint[]
       )
       OR NOT EXISTS (
           SELECT 1
             FROM pg_constraint AS constraint_definition
            WHERE constraint_definition.conrelid = 'public.registered_web_services'::regclass
              AND constraint_definition.conname = 'registered_web_services_logout_return_uri_not_empty'
              AND constraint_definition.contype = 'c'
              AND constraint_definition.convalidated
              AND constraint_definition.conkey = ARRAY[
                  (SELECT attnum FROM pg_attribute
                    WHERE attrelid = 'public.registered_web_services'::regclass
                      AND attname = 'logout_return_uri')
              ]::smallint[]
       )
       OR NOT EXISTS (
           SELECT 1
             FROM pg_constraint AS constraint_definition
            WHERE constraint_definition.conrelid = 'public.registered_web_services'::regclass
              AND constraint_definition.conname = 'registered_web_services_service_secret_sha256_length'
              AND constraint_definition.contype = 'c'
              AND constraint_definition.convalidated
              AND constraint_definition.conkey = ARRAY[
                  (SELECT attnum FROM pg_attribute
                    WHERE attrelid = 'public.registered_web_services'::regclass
                      AND attname = 'service_secret_sha256')
              ]::smallint[]
       ) THEN
        RAISE EXCEPTION
            'authentication table structure mismatch: check constraints';
    END IF;

    IF (SELECT count(*) FROM pg_index
         WHERE indrelid IN (
             'public.internal_users'::regclass,
             'public.external_identities'::regclass,
             'public.registered_web_services'::regclass
         )) <> 4
       OR NOT EXISTS (
           SELECT 1
             FROM pg_index AS index_definition
             JOIN pg_class AS index_relation
               ON index_relation.oid = index_definition.indexrelid
             JOIN pg_am AS access_method
               ON access_method.oid = index_relation.relam
            WHERE index_definition.indrelid = 'public.external_identities'::regclass
              AND index_relation.relname = 'external_identities_internal_user_id_idx'
              AND access_method.amname = 'btree'
              AND index_definition.indisvalid
              AND index_definition.indisready
              AND index_definition.indislive
              AND NOT index_definition.indisunique
              AND NOT index_definition.indisprimary
              AND index_definition.indpred IS NULL
              AND index_definition.indexprs IS NULL
              AND index_definition.indnkeyatts = 1
              AND index_definition.indnatts = 1
              AND (
                  SELECT key_column.attnum
                    FROM unnest(index_definition.indkey::smallint[])
                         WITH ORDINALITY AS key_column(attnum, position)
                   WHERE key_column.position = 1
              ) = (
                  SELECT attnum FROM pg_attribute
                   WHERE attrelid = 'public.external_identities'::regclass
                     AND attname = 'internal_user_id'
              )
       ) THEN
        RAISE EXCEPTION
            'authentication table structure mismatch: required indexes';
    END IF;

    EXECUTE $temporary$
        CREATE TEMP TABLE t05_internal_users_validation (
            LIKE public.internal_users INCLUDING DEFAULTS INCLUDING IDENTITY INCLUDING CONSTRAINTS
        ) ON COMMIT DROP
    $temporary$;
    INSERT INTO t05_internal_users_validation DEFAULT VALUES
        RETURNING is_enabled, created_at INTO validation_enabled, validation_time;
    IF validation_enabled IS DISTINCT FROM true
       OR validation_time IS NULL
       OR validation_time < clock_timestamp() - interval '5 minutes'
       OR validation_time > clock_timestamp() + interval '5 seconds' THEN
        RAISE EXCEPTION
            'authentication table structure mismatch: internal_users defaults';
    END IF;

    EXECUTE $temporary$
        CREATE TEMP TABLE t05_external_identities_validation (
            LIKE public.external_identities INCLUDING DEFAULTS INCLUDING IDENTITY INCLUDING CONSTRAINTS
        ) ON COMMIT DROP
    $temporary$;
    BEGIN
        INSERT INTO t05_external_identities_validation (provider, subject, internal_user_id)
            VALUES ('p', 's', 1)
            RETURNING linked_at INTO validation_time;
    EXCEPTION WHEN check_violation THEN
        RAISE EXCEPTION
            'authentication table structure mismatch: external_identities check behavior';
    END;
    IF validation_time IS NULL
       OR validation_time < clock_timestamp() - interval '5 minutes'
       OR validation_time > clock_timestamp() + interval '5 seconds' THEN
        RAISE EXCEPTION
            'authentication table structure mismatch: external_identities linked_at default';
    END IF;
    INSERT INTO t05_external_identities_validation (provider, subject, internal_user_id)
        VALUES (' ', ' ', 1);
    BEGIN
        INSERT INTO t05_external_identities_validation (provider, subject, internal_user_id)
            VALUES ('', 'nonempty-subject', 1);
        RAISE EXCEPTION 'empty provider check did not reject input';
    EXCEPTION WHEN check_violation THEN
        NULL;
    END;
    BEGIN
        INSERT INTO t05_external_identities_validation (provider, subject, internal_user_id)
            VALUES ('nonempty-provider', '', 1);
        RAISE EXCEPTION 'empty subject check did not reject input';
    EXCEPTION WHEN check_violation THEN
        NULL;
    END;

    EXECUTE $temporary$
        CREATE TEMP TABLE t05_registered_web_services_validation (
            LIKE public.registered_web_services INCLUDING DEFAULTS INCLUDING IDENTITY INCLUDING CONSTRAINTS
        ) ON COMMIT DROP
    $temporary$;
    INSERT INTO t05_registered_web_services_validation (
        service_id,
        login_callback_uri,
        logout_return_uri,
        service_secret_sha256
    ) VALUES (
        'service_1',
        'https://callback.example.test',
        'https://logout.example.test',
        decode(repeat('ab', 32), 'hex')
    ) RETURNING is_enabled, created_at INTO validation_enabled, validation_time;
    IF validation_enabled IS DISTINCT FROM true
       OR validation_time IS NULL
       OR validation_time < clock_timestamp() - interval '5 minutes'
       OR validation_time > clock_timestamp() + interval '5 seconds' THEN
        RAISE EXCEPTION
            'authentication table structure mismatch: registered_web_services defaults';
    END IF;
    INSERT INTO t05_registered_web_services_validation (
        service_id, login_callback_uri, logout_return_uri, service_secret_sha256
    ) VALUES (
        repeat('a', 64), 'https://callback.example.test',
        'https://logout.example.test', decode(repeat('ab', 32), 'hex')
    );
    BEGIN
        INSERT INTO t05_registered_web_services_validation (
            service_id, login_callback_uri, logout_return_uri, service_secret_sha256
        ) VALUES (
            '_invalid', 'https://callback.example.test',
            'https://logout.example.test', decode(repeat('ab', 32), 'hex')
        );
        RAISE EXCEPTION 'invalid service_id prefix check did not reject input';
    EXCEPTION WHEN check_violation THEN
        NULL;
    END;
    BEGIN
        INSERT INTO t05_registered_web_services_validation (
            service_id, login_callback_uri, logout_return_uri, service_secret_sha256
        ) VALUES (
            'invalid!', 'https://callback.example.test',
            'https://logout.example.test', decode(repeat('ab', 32), 'hex')
        );
        RAISE EXCEPTION 'invalid service_id character check did not reject input';
    EXCEPTION WHEN check_violation THEN
        NULL;
    END;
    BEGIN
        INSERT INTO t05_registered_web_services_validation (
            service_id, login_callback_uri, logout_return_uri, service_secret_sha256
        ) VALUES (
            repeat('a', 65), 'https://callback.example.test',
            'https://logout.example.test', decode(repeat('ab', 32), 'hex')
        );
        RAISE EXCEPTION 'long service_id check did not reject input';
    EXCEPTION WHEN check_violation THEN
        NULL;
    END;
    BEGIN
        INSERT INTO t05_registered_web_services_validation (
            service_id, login_callback_uri, logout_return_uri, service_secret_sha256
        ) VALUES (
            'empty-callback', '', 'https://logout.example.test',
            decode(repeat('ab', 32), 'hex')
        );
        RAISE EXCEPTION 'empty login callback URI check did not reject input';
    EXCEPTION WHEN check_violation THEN
        NULL;
    END;
    BEGIN
        INSERT INTO t05_registered_web_services_validation (
            service_id, login_callback_uri, logout_return_uri, service_secret_sha256
        ) VALUES (
            'empty-logout', 'https://callback.example.test', '',
            decode(repeat('ab', 32), 'hex')
        );
        RAISE EXCEPTION 'empty logout return URI check did not reject input';
    EXCEPTION WHEN check_violation THEN
        NULL;
    END;
    BEGIN
        INSERT INTO t05_registered_web_services_validation (
            service_id, login_callback_uri, logout_return_uri, service_secret_sha256
        ) VALUES (
            'secret-31', 'https://callback.example.test',
            'https://logout.example.test', decode(repeat('ab', 31), 'hex')
        );
        RAISE EXCEPTION '31-byte secret check did not reject input';
    EXCEPTION WHEN check_violation THEN
        NULL;
    END;
    BEGIN
        INSERT INTO t05_registered_web_services_validation (
            service_id, login_callback_uri, logout_return_uri, service_secret_sha256
        ) VALUES (
            'secret-33', 'https://callback.example.test',
            'https://logout.example.test', decode(repeat('ab', 33), 'hex')
        );
        RAISE EXCEPTION '33-byte secret check did not reject input';
    EXCEPTION WHEN check_violation THEN
        NULL;
    END;
END
$$;
