apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: auth0
configMapGenerator:
- name: nodejs-app-login
  files: 
  - src/server.js
  - src/index.html
resources:
- ./yaml/nodejs.yaml
- ./yaml/create_namespace.yaml
