apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: auth0

resources:
  - frontend-configmap.yaml
  - frontend-deployment.yaml
  - frontend-service.yaml
  # - ../../portal_backend/k8s/backend-configmap.yaml
  # - ../../portal_backend/k8s/deploy.yaml
  # - ../../portal_backend/k8s/service.yaml
  # - ../../portal_backend/k8s/backend-networkpolicy.yaml
  - ingress.yaml

labels:
- pairs:
    project: portal
    environment: production