apiVersion: v1
kind: Service
metadata:
  name: uniauth
  namespace: auth0
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"name":"uniauth","namespace":"auth0"},"spec":{"ports":[{"port":8080,"protocol":"TCP","targetPort":8080}],"selector":{"app":"uniauth"}}}
spec:
  type: ClusterIP
  selector:
    app: uniauth
  ports:
    - port: 8081
      targetPort: 8081
      protocol: TCP
  sessionAffinity: None
  ipFamilyPolicy: SingleStack
  ipFamilies:
    - IPv4
  internalTrafficPolicy: Cluster
